const {PGlite}=await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
const root=new URL('../',import.meta.url);
try {
 await db.exec(fs.readFileSync(new URL('tests/fixtures/pacotes_schema.sql',root),'utf8'));
 await db.exec(fs.readFileSync(new URL('SUPABASE_SQL/pacotes_contrato_canonico.sql',root),'utf8'));
 const cid='11111111-1111-4111-8111-111111111111',proc='22222222-2222-4222-8222-222222222222';
 await db.exec(`set test.clinica='${cid}';set test.papel='MASTER';insert into clinicas(id) values('${cid}');insert into pacientes(id,clinica_id,nome) values('teste','${cid}','Teste');insert into procedimentos(id,clinica_id,nome,valor,sessoes_pacote,ativo) values('${proc}','${cid}','Pacote teste',123,10,true);`);
 const call=async(op,custom=null)=>(await db.query('select kinesys_contratar_pacote($1,$2,$3,$4) c',['teste',proc,op,custom])).rows[0].c;
 const a=await call('contrato1');assert.equal(a.valor_final,123);assert.equal(a.sessoes_contratadas,10);
 assert.equal((await call('contrato1')).id,a.id);
 await db.exec(`update procedimentos set valor=234 where id='${proc}'`);
 const b=await call('contrato2');assert.equal(b.valor_final,234);
 assert.equal((await db.query('select valor_final from planos_atendimento where id=$1',[a.id])).rows[0].valor_final,'123');
 const alter=async(id,acao,custom=null)=>(await db.query('select kinesys_alterar_contrato($1,$2,$3,$4) c',[id,acao,'Teste de regras',custom])).rows[0].c;
 const customized=await alter(a.id,'personalizar',{sessoes:6,valor:111});assert.equal(customized.sessoes_contratadas,6);assert.equal(customized.valor_final,111);
 const restored=await alter(a.id,'remover_personalizacao');assert.equal(restored.sessoes_contratadas,10);assert.equal(restored.valor_final,123);
 const appointment=async(id,status,plan)=>db.query('insert into agendamentos(id,paciente_id,procedimento_id,clinica_id,plano_id,status) values($1,$2,$3,$4,$5,$6)',[id,'teste',proc,cid,plan,status]);
 await assert.rejects(appointment('33333333-3333-4333-8333-333333333333','atendido',null),/Contrate/);
 for(let i=1;i<=10;i++)await appointment(`33333333-3333-4333-8333-${String(i).padStart(12,'0')}`,'agendado',a.id);
 await assert.rejects(appointment('33333333-3333-4333-8333-999999999999','agendado',a.id),/reservadas/);
 await db.exec(`update agendamentos set status='atendido' where plano_id='${a.id}'`);
 assert.equal((await db.query('select status from planos_atendimento where id=$1',[a.id])).rows[0].status,'concluido');
 await db.exec(`update agendamentos set status='cancelado' where id='33333333-3333-4333-8333-000000000001'`);
 assert.equal((await db.query('select status from planos_atendimento where id=$1',[a.id])).rows[0].status,'ativo');
 await alter(b.id,'cancelar');
 await assert.rejects(db.query("update planos_atendimento set status='ativo' where id=$1",[b.id]),/reativado/);
 await assert.rejects(db.query('delete from planos_atendimento where id=$1',[b.id]),/Cancele/);
 const individual='44444444-4444-4444-8444-444444444444',ag='55555555-5555-4555-8555-555555555555';
 await db.exec(`insert into procedimentos(id,clinica_id,nome,valor,sessoes_pacote,ativo) values('${individual}','${cid}','Individual',85,1,true);insert into agendamentos(id,paciente_id,procedimento_id,clinica_id,status) values('${ag}','teste','${individual}','${cid}','agendado');`);
 const c=(await db.query('select kinesys_preparar_cobranca_agendamento($1) c',[ag])).rows[0].c;
 const payment='66666666-6666-4666-8666-666666666666';
 await db.query("insert into pagamentos(id,plano_id,paciente_id,clinica_id,valor,tipo,agendamento_id,cobranca_agendamento_id) values($1,$2,'teste',$3,85,'recebimento',$4,$5)",[payment,c.plano_id,cid,ag,c.id]);
 await assert.rejects(db.query("select kinesys_baixar_cobranca_agendamento($1,'migracao_pacote','Teste')",[ag]),/Estorne/);
 await assert.rejects(db.query('select kinesys_vincular_contrato($1,$2)',[ag,a.id]),/Estorne/);
 await db.query("select kinesys_estornar_pagamento($1,'Teste de estorno')",[payment]);
 await db.query('select kinesys_vincular_contrato($1,$2)',[ag,a.id]);
 const result=(await db.query('select * from cobrancas_agendamento where id=$1',[c.id])).rows[0];assert.equal(Number(result.valor_devido),0);assert.equal(result.baixa_tipo,'migracao_pacote');
 assert.equal((await db.query('select valor_final from planos_atendimento where id=$1',[a.id])).rows[0].valor_final,'123');
 assert.equal((await db.query('select count(*) n from pagamentos where cobranca_agendamento_id=$1',[c.id])).rows[0].n,2);
 const sit=(await db.query('select * from kinesys_situacao_financeira_agendamentos($1)',[[ag]])).rows[0];assert.equal(sit.origem,'plano');assert.equal(sit.valor_devido,'123');
 const again=(await db.query("select kinesys_baixar_cobranca_agendamento($1,'migracao_pacote','Teste') c",[ag])).rows[0].c;assert.equal(again.repetido,true);
 const orphan='77777777-7777-4777-8777-777777777777';
 await db.exec(`insert into agendamentos(id,paciente_id,procedimento_id,clinica_id,status) values('${orphan}','teste','${individual}','${cid}','agendado');`);
 const oc=(await db.query('select kinesys_preparar_cobranca_agendamento($1) c',[orphan])).rows[0].c;
 await db.exec(`delete from agendamentos where id='${orphan}'`);
 assert.equal((await db.query("select kinesys_baixar_cobranca_agendamento($1,'lancamento_incorreto','Teste órfão') c",[orphan])).rows[0].c.ok,true);
 const legacy=(await db.query("insert into planos_atendimento(paciente_id,procedimento_id,clinica_id,nome,sessoes_contratadas,valor_tabela,valor_final,status,operacao_id) values('teste',$1,$2,'Legado',1,234,234,'concluido','unitario-agenda-88888888-8888-4888-8888-888888888888') returning id",[proc,cid])).rows[0].id;
 await db.query("insert into agendamentos(id,paciente_id,procedimento_id,clinica_id,plano_id,status) values('88888888-8888-4888-8888-888888888888','teste',$1,$2,$3,'cancelado')",[proc,cid,legacy]);
 const lc=(await db.query("insert into cobrancas_agendamento(clinica_id,agendamento_id,paciente_id,procedimento_id,plano_id,valor_original,desconto_valor,origem) values($1,'88888888-8888-4888-8888-888888888888','teste',$2,$3,234,0,'unitario') returning id",[cid,proc,legacy])).rows[0].id;
 const lp=(await db.query("insert into pagamentos(plano_id,paciente_id,clinica_id,valor,tipo,agendamento_id,cobranca_agendamento_id) values($1,'teste',$2,234,'recebimento','88888888-8888-4888-8888-888888888888',$3) returning id",[legacy,cid,lc])).rows[0].id;
 await db.query("select kinesys_estornar_pagamento($1,'Teste reparação')",[lp]);
 await db.exec(fs.readFileSync(new URL('SUPABASE_SQL/pacotes_reparar_unitario_estornado.sql',root),'utf8'));
 assert.equal(Number((await db.query('select valor_devido from cobrancas_agendamento where id=$1',[lc])).rows[0].valor_devido),0);
 assert.equal((await db.query('select count(*) n from pagamentos where plano_id=$1',[legacy])).rows[0].n,2);
 await db.exec("set test.papel='FISIOTERAPEUTA'");await assert.rejects(call('unauthorized'),/administradores/);
 console.log('PASS: contratação, idempotência, preço vigente/histórico, personalização substitutiva, restauração, zero sem contrato, reservas, excesso bloqueado, consumo, reversão, cancelamento, proteção de cache e autorização.');
}catch(e){console.error(e.message,e.detail||'',e.where||'');process.exitCode=1;}finally{await db.close();}
