/* Diferenciais periféricos e dor referida — KineSys 1.7.
   Estes itens ajudam a organizar diferenciais; não são diagnósticos automáticos. */
(function(){
 if(typeof BANCO_MAPEAMENTO_CLINICO==='undefined')return;
 function add(reg,id,nome,testes,interpretacao,extras={}){
   const r=BANCO_MAPEAMENTO_CLINICO[reg];if(!r)return;if(!Array.isArray(r.diferenciais))r.diferenciais=[];
   if(r.diferenciais.some(x=>x.id===id)||(r.clusters||[]).some(x=>x.id===id))return;
   r.diferenciais.push({id,nome,testes,interpretacao,...extras});
 }
 add('ombro','neuropatia_supraescapular','Neuropatia do Nervo Supraescapular — diferencial',[ 'Dor posterior/superior do ombro com distribuição compatível', 'Fraqueza de rotação externa e/ou abdução não explicada apenas por dor', 'Atrofia de supra/infraespinal ou contexto de tração/compressão do nervo' ],'Considere neuropatia supraescapular quando dor posterior do ombro e déficit motor/atrofia forem coerentes; correlacione com exame neurológico e, quando necessário, investigação complementar.',{palavrasChaveHMA:['dor posterior ombro','fraqueza rotacao externa','atrofia infraespinhal'],tipoDorPreferido:['neuropatica','mista']});
 add('cotovelo','pronador_mediano','Síndrome do Pronador / Neuropatia Proximal do Mediano',[ 'Dor volar/proximal do antebraço agravada por pronação resistida ou esforço repetitivo', 'Parestesia em distribuição do mediano incluindo possível palma/eminência tenar', 'Diferenciação de túnel do carpo e radiculopatia cervical' ],'Padrão compatível com compressão proximal do nervo mediano deve ser diferenciado de túnel do carpo, radiculopatia cervical e outras neuropatias.',{palavrasChaveHMA:['dor antebraco pronacao','parestesia mediano','pronador'],tipoDorPreferido:['neuropatica']});
 add('quadril','deep_gluteal','Síndrome Glútea Profunda / Aprisionamento Não Discogênico do Ciático',[ 'Dor profunda glútea com possível irradiação posterior', 'Piora sentada e/ou com posições que tensionam estruturas glúteas profundas', 'Exame lombar e neurológico para diferenciar origem radicular' ],'Síndrome glútea profunda descreve aprisionamento não discogênico do ciático no espaço glúteo profundo; deve ser diferenciada de radiculopatia lombar e patologia do quadril.',{palavrasChaveHMA:['dor glutea piora sentado','gluteo posterior coxa','piriforme'],tipoDorPreferido:['neuropatica','mista']});
 add('quadril','hamstring_proximal_neural','Isquiotibiais Proximais / Interface com Nervo Ciático',[ 'Dor na tuberosidade isquiática ou glúteo inferior', 'Dor reproduzida por carga de isquiotibiais/flexão de quadril e frequentemente por sedestação', 'Pesquisar sintomas neurais quando houver irradiação distal' ],'Diferencie tendinopatia/lesão proximal dos isquiotibiais de síndrome glútea profunda e radiculopatia quando houver sintomas posteriores irradiados.',{palavrasChaveHMA:['dor isquio sentado','posterior coxa corrida','tuberosidade isquiatica']});
 add('quadril','meralgia_parestetica','Meralgia Parestésica — Nervo Cutâneo Femoral Lateral',[ 'Queimação/parestesia na face anterolateral da coxa', 'Ausência de déficit motor atribuível ao nervo cutâneo femoral lateral', 'Considerar compressão junto ao ligamento inguinal e diferenciar de radiculopatia' ],'Padrão sensitivo anterolateral isolado da coxa é compatível com investigação de meralgia parestésica.',{palavrasChaveHMA:['queimacao lateral coxa','parestesia anterolateral coxa'],tipoDorPreferido:['neuropatica']});
 add('quadril','neuropatia_femoral','Neuropatia Femoral — diferencial',[ 'Alteração sensitiva anterior da coxa/perna medial conforme distribuição', 'Fraqueza de quadríceps/extensão do joelho', 'Reflexo patelar reduzido e diferenciação de raízes L2-L4' ],'Déficit motor de quadríceps associado a alterações sensitivas/reflexas exige diferenciação entre neuropatia femoral, plexopatia e radiculopatia L2-L4.',{tipoDorPreferido:['neuropatica']});
 add('quadril','neuropatia_obturatoria','Neuropatia Obturatória — diferencial',[ 'Dor/parestesia medial da coxa', 'Fraqueza de adução do quadril', 'Diferenciação de lesão adutora, quadril e radiculopatia' ],'Considere neuropatia obturatória em sintomas mediais da coxa associados a déficit de adução e contexto compatível.',{tipoDorPreferido:['neuropatica']});
 add('joelho','neuropatia_safeno','Neuropatia do Nervo Safeno — diferencial',[ 'Dor/parestesia medial de joelho e perna sem déficit motor', 'Sensibilidade ao longo do canal dos adutores/região safena conforme contexto', 'Diferenciação de joelho local e radiculopatia L3-L4' ],'O safeno é sensitivo; sintomas mediais sem fraqueza correspondente podem justificar investigação periférica.',{tipoDorPreferido:['neuropatica']});
 add('joelho','neuropatia_fibular_comum','Neuropatia do Nervo Fibular Comum',[ 'Sintomas junto à cabeça da fíbula com extensão à perna lateral/dorso do pé', 'Fraqueza de dorsiflexão e/ou eversão; pesquisar pé caído', 'Diferenciação de radiculopatia L5 e lesões mais distais do fibular' ],'Pé caído ou déficit de dorsiflexão/eversão requer localização neurológica cuidadosa entre nervo fibular, raiz L5 e outras causas.',{tipoDorPreferido:['neuropatica']});
 add('tornozelo_pe','tunel_tarsal_neural','Síndrome do Túnel do Tarso / Neuropatia Tibial',[ 'Dor/queimação ou parestesia posterior ao maléolo medial', 'Irradiação para planta do pé/dedos conforme distribuição tibial', 'Provocação local e diferenciação de radiculopatia S1/S2 e causas plantares' ],'Sintomas plantares neuropáticos originados no tornozelo medial podem justificar investigação do nervo tibial/túnel do tarso.',{tipoDorPreferido:['neuropatica']});
 add('tornozelo_pe','fibular_superficial','Neuropatia do Nervo Fibular Superficial',[ 'Parestesia/dor em perna anterolateral e dorso do pé', 'Distribuição costuma poupar o primeiro espaço interdigital', 'Avaliar eversão e diferenciar de L5/fibular comum' ],'Localize a lesão comparando distribuição sensitiva, força e sítio de provocação.',{tipoDorPreferido:['neuropatica']});
 add('tornozelo_pe','fibular_profundo','Neuropatia do Nervo Fibular Profundo / Túnel Tarsal Anterior',[ 'Sintomas dorsais no tornozelo/pé com parestesia no primeiro espaço interdigital', 'Possível associação a compressão por calçado/retináculo', 'Diferenciação de L5 e fibular comum' ],'Parestesia focal no primeiro espaço interdigital é uma pista de distribuição do fibular profundo, sempre correlacionada ao exame.',{tipoDorPreferido:['neuropatica']});
 add('tornozelo_pe','neuropatia_sural','Neuropatia do Nervo Sural — diferencial',[ 'Dor/parestesia posterolateral da panturrilha/tornozelo', 'Irradiação para maléolo lateral e borda lateral do pé', 'Ausência de déficit motor atribuível ao sural' ],'O sural é predominantemente sensitivo; diferencie de S1 e de outras neuropatias periféricas.',{tipoDorPreferido:['neuropatica']});
 add('coluna_toracica','neuralgia_intercostal','Neuralgia Intercostal / Dor em Faixa',[ 'Dor em faixa seguindo espaço intercostal', 'Qualidade queimante/choque ou alodinia', 'Triagem de causas cardiopulmonares, viscerais e herpes-zóster conforme contexto' ],'Dor em faixa torácica pode ser neuropática/intercostal, mas exige exclusão de causas não musculoesqueléticas relevantes.',{tipoDorPreferido:['neuropatica']});
})();
