const fs=require('fs');
function load(path){return fs.readFileSync(path,'utf8');}
function save(path,s){fs.writeFileSync(path,s);}
function must(s,needle,label){if(!s.includes(needle))throw new Error('Marcador não encontrado: '+label);}
function before(s,marker,addition,label){must(s,marker,label);return s.replace(marker,addition+'\n'+marker);}

// ELBOW
{
 const path='clinical_reasoning_elbow-3.1.0.js';let s=load(path);
 if(!s.includes("const VERSION='3.1.2-elbow3'")){
  must(s,"const VERSION='3.1.1-elbow2';",'elbow version');s=s.replace("const VERSION='3.1.1-elbow2';","const VERSION='3.1.2-elbow3';");
  s=before(s,"    {id:'cotovelo_lateral',ordem:88",`    {id:'cotovelo_plri',ordem:93,nomes:[/instabilidade posterolateral|plri|lucl|rotatoria posterolateral/],rotulo:'Instabilidade rotatória posterolateral (PLRI/LUCL) — investigar',termos:['cotovelo dando falseio','cotovelo cede quando apoio','clunk no cotovelo ao apoiar','inseguranca para empurrar depois de luxacao','cotovelo instavel depois de deslocar','falseio depois de luxacao do cotovelo'],perguntas:['Houve luxação/trauma prévio e desde então sensação de falseio, apreensão ou instabilidade?','Apoiar a mão para levantar da cadeira, fazer flexão ou empurrar provoca clunk/falseio mais do que dor tendínea focal?','Há deformidade atual ou incapacidade aguda que obrigue excluir nova fratura/luxação antes de testar estabilidade?'],objetivos:['História de luxação/trauma e episódios de instabilidade','Avaliar apreensão/falseio em carga axial e extensão com progressão cautelosa','Chair push-up/tabletop relocation ou pivot-shift apenas quando apropriado e seguro','Diferenciar PLRI de epicondilalgia lateral, túnel radial e componente articular'],reforca:['luxação/trauma prévio','falseio/apreensão','clunk em carga axial'],enfraquece:['dor focal estável reproduzida apenas por carga extensora sem instabilidade']},`,'insert PLRI');
  s=before(s,"    cotovelo_lateral:{essencial:",`    cotovelo_plri:{essencial:['História de luxação/trauma e sensação de falseio/apreensão','Carga axial em extensão com observação de instabilidade quando segura','Comparar com carga extensora focal e exame radiocapitellar/articular'],complementar:['Chair push-up/tabletop relocation','Pivot-shift posterolateral por examinador experiente quando apropriado','Imagem estática/dinâmica quando a decisão clínica exigir'],evitar:['Não provocar instabilidade vigorosamente em trauma agudo ou cotovelo ainda não esclarecido']},`,'PLRI matrix');
  const oldVars=`    const lateralAnatomica=/(?:lateral|lado de fora|epicondilo lateral).{0,28}cotovelo|cotovelo.{0,28}(?:lateral|lado de fora|epicondilo lateral)/.test(t);\n    const cargaExtensoraLocal=/(?:cotovelo).{0,65}(?:apert|preens|estend.{0,12}punho)|(?:apert|preens|estend.{0,12}punho).{0,65}cotovelo/.test(t);\n    const localLateral=lateralAnatomica||cargaExtensoraLocal;\n    const localMedial=/(?:medial|lado de dentro|epicondilo medial).{0,55}cotovelo|cotovelo.{0,55}(?:medial|lado de dentro)/.test(t);`;
  const newVars=`    const localizacaoIncerta=/(?:nao sei|nao sabe|nao consigo dizer).{0,45}(?:lado|dentro|fora|medial|lateral)|(?:dentro|fora|medial|lateral).{0,45}(?:nao sei|nao sabe)/.test(t);\n    const lateralAnatomica=!localizacaoIncerta&&(/(?:lateral|lado de fora|epicondilo lateral).{0,28}cotovelo|cotovelo.{0,28}(?:lateral|lado de fora|epicondilo lateral)/.test(t));\n    const cargaExtensoraLocal=/(?:cotovelo).{0,65}(?:apert|preens|estend.{0,12}punho)|(?:apert|preens|estend.{0,12}punho).{0,65}cotovelo/.test(t);\n    const cargaExtensoraNegada=/(?:apert|preens|estend.{0,15}punho).{0,32}(?:nao muda|nao piora|nao doi|quase nao|sem dor)|(?:nao muda|nao piora|nao doi|quase nao|sem dor).{0,32}(?:apert|preens|estend.{0,15}punho)/.test(t);\n    const cargaExtensoraPositiva=cargaExtensoraLocal&&!cargaExtensoraNegada;\n    const localLateral=lateralAnatomica;\n    const localMedial=!localizacaoIncerta&&(/(?:medial|lado de dentro|parte de dentro|epicondilo medial).{0,55}cotovelo|cotovelo.{0,55}(?:medial|lado de dentro|parte de dentro)/.test(t));\n    const cargaFlexorPronadoraBruta=/(?:flexion|flexao|flexionar).{0,20}punho|pron(?:ar|acao)|punho.{0,20}(?:flexion|flexao)/.test(t);\n    const cargaFlexorPronadoraNegada=/(?:flexion|flexao|flexionar|pron(?:ar|acao)).{0,35}(?:nao muda|nao piora|nao doi|sem dor)|(?:nao muda|nao piora|nao doi|sem dor).{0,35}(?:flexion|flexao|flexionar|pron(?:ar|acao))/.test(t);\n    const cargaFlexorPronadora=cargaFlexorPronadoraBruta&&!cargaFlexorPronadoraNegada;\n    const rotuloTendineoIsolado=/(?:disseram|medico|doutor|laudo).{0,50}(?:epicondilit|tendinit|cotovelo de tenista|cotovelo de golfista)/.test(t)&&/(?:so sei|nao sei onde|nao sei dizer|nao sabe dizer)/.test(t);\n    const padraoRadialDistal=/(?:mais para baixo|abaixo|distal|antebraco).{0,65}(?:epicond|cotovelo|lateral)|(?:lateral).{0,65}(?:antebraco|abaixo|distal)/.test(t);\n    const padraoPLRI=/(?:falseio|cede|cedendo|insegur|instavel|clunk).{0,90}(?:cotovelo|apoi|cadeira|empurr)|(?:cotovelo|apoi|cadeira|empurr).{0,90}(?:falseio|cede|insegur|instavel|clunk)/.test(t);\n    const historiaPLRI=/(?:lux|desloc|trauma|queda).{0,130}(?:falseio|cede|insegur|instavel|clunk)|(?:falseio|cede|insegur|instavel|clunk).{0,130}(?:lux|desloc|trauma|queda)/.test(t);`;
  must(s,oldVars,'elbow scoring vars');s=s.replace(oldVars,newVars);
  const oldRules=`    if(cond.id==='cotovelo_lateral'&&localLateral)score+=2.8;\n    if(cond.id==='cotovelo_lateral'&&relacaoOmbro&&/lateral do braco/.test(t)&&!cargaExtensoraLocal)score-=3.2;\n    if(cond.id==='cotovelo_medial'&&localMedial)score+=2.8;`;
  const newRules=`    if(cond.id==='cotovelo_plri'){if(padraoPLRI&&historiaPLRI){score+=5.8;hits.push('instabilidade dinâmica após trauma/luxação');}else if(padraoPLRI){score+=2.8;hits.push('falseio/clunk em carga');}}\n    if(cond.id==='cotovelo_lateral'){\n      if(localLateral&&cargaExtensoraPositiva)score+=3.4;else if(localLateral)score+=0.7;\n      if((neuroDistal||cervicalLigada||articular)&&!cargaExtensoraPositiva)score-=3.2;\n      if(padraoRadialDistal&&cargaSupinacao)score-=3.2;\n      if(rotuloTendineoIsolado)score=-5;\n    }\n    if(cond.id==='cotovelo_lateral'&&relacaoOmbro&&/lateral do braco/.test(t)&&!cargaExtensoraPositiva)score-=3.2;\n    if(cond.id==='cotovelo_medial'){\n      if(localMedial&&cargaFlexorPronadora)score+=3.4;else if(localMedial)score+=0.7;\n      if((digitosUlnares||arremessoValgo)&&!cargaFlexorPronadora)score-=3.2;\n      if(rotuloTendineoIsolado)score=-5;\n    }`;
  must(s,oldRules,'elbow tendon rules');s=s.replace(oldRules,newRules);
  const oldReturn=`    return {score:score+cond.ordem/1000,hits:uniq(hits).slice(0,6)};`;
  const newReturn=`    const evidenciaForte=cond.id==='cotovelo_lateral'?(localLateral&&cargaExtensoraPositiva&&!rotuloTendineoIsolado):cond.id==='cotovelo_medial'?(localMedial&&cargaFlexorPronadora&&!rotuloTendineoIsolado):true;\n    return {score:score+cond.ordem/1000,hits:uniq(hits).slice(0,6),evidenciaForte};`;
  must(s,oldReturn,'elbow return');s=s.replace(oldReturn,newReturn);
  const oldFilter=`let fortes=avaliadas.filter(x=>x.hits.length||x.score>=2.5).slice(0,7);`;
  const newFilter=`let fortes=avaliadas.filter(x=>{if(x.cond.id==='cotovelo_lateral'||x.cond.id==='cotovelo_medial')return x.evidenciaForte&&x.score>=2.5;return x.hits.length||x.score>=2.5;}).slice(0,7);`;
  must(s,oldFilter,'elbow filter');s=s.replace(oldFilter,newFilter);
  save(path,s);
 }
}

// SHOULDER
{
 const path='clinical_reasoning_shoulder-3.1.0.js';let s=load(path);
 if(!s.includes("const VERSION='3.1.4-shoulder5'")){
  must(s,"const VERSION='3.1.3-shoulder4';",'shoulder version');s=s.replace("const VERSION='3.1.3-shoulder4';","const VERSION='3.1.4-shoulder5';");
  s=before(s,"    {\n      id:'ombro_trauma_maior'",`    {\n      id:'ombro_cardiorrespiratorio', ordem:115, urgente:true,\n      nomes:[/cardiac|cardiopulmonar|dor referida visceral|angina/],\n      rotulo:'Origem cardiorrespiratória/visceral — excluir prioritariamente',\n      termos:['dor no ombro com pressao no peito','dor no ombro com falta de ar','ombro esquerdo durante esforco com suor frio','dor no ombro ao subir ladeira com nausea'],\n      perguntas:['A dor aparece com esforço cardiovascular e melhora ao interromper o esforço?','Há pressão/dor torácica, dispneia, sudorese fria, náusea, tontura ou mal-estar?','O movimento/carga local do ombro reproduz a mesma dor independentemente do esforço?'],\n      objetivos:['Priorizar sinais vitais e triagem de causa não musculoesquelética','Não atrasar avaliação médica/urgência quando o padrão cardiorrespiratório for plausível','Somente prosseguir para provocação musculoesquelética quando a segurança estiver esclarecida'],\n      reforca:['relação com esforço','dor/pressão torácica','dispneia/sudorese/náusea'],\n      enfraquece:['dor local claramente reprodutível sem sintomas sistêmicos ou relação com esforço']\n    },`,'insert shoulder cardio');
  s=before(s,"    ombro_trauma_maior:{",`    ombro_cardiorrespiratorio:{\n      essencial:['Relação com esforço cardiovascular','Dor/pressão torácica, dispneia, sudorese, náusea/tontura e sinais vitais','Decisão de encaminhamento médico/urgência antes de testes locais'],\n      complementar:['Reprodução musculoesquelética somente após triagem de segurança'],\n      evitar:['Não atribuir dor no ombro a manguito/bíceps quando houver padrão cardiorrespiratório plausível']\n    },`,'shoulder cardio matrix');
  const oldElev=`    const elevacao=/(?:levantar|levanto|elev|ergu|acima da cabeca|no alto|prateleira|armario)/.test(t);`;
  const newElev=`    const elevacao=/(?:levantar|levanto|elev|ergu|acima da cabeca|no alto|prateleira|armario)/.test(t);\n    const elevacaoNegada=/(?:levantar|elevar|erguer).{0,38}(?:nao muda|nao piora|nao reproduz|nao doi|sem dor)|(?:nao muda|nao piora|nao reproduz|nao doi).{0,38}(?:levantar|elevar|erguer)/.test(t);\n    const toracico=/(?:dor|pressao|aperto|peso).{0,35}(?:peito|torax)|(?:peito|torax).{0,35}(?:dor|pressao|aperto|peso)/.test(t);\n    const esforcoCardio=/(?:subir|ladeira|escada|caminhar|correr|esforco|atividade fisica)/.test(t);\n    const associadosCardio=/(?:falta de ar|dispneia|suor frio|sudorese|nausea|enjoo|tontura)/.test(t);`;
  must(s,oldElev,'shoulder variables');s=s.replace(oldElev,newElev);
  const oldPmr=`    if(cond.id==='ombro_pmr'&&idade>=50)score+=2;`;
  const newPmr=`    if(cond.id==='ombro_cardiorrespiratorio'&&temOmbro&&toracico&&esforcoCardio&&associadosCardio){score+=7;hits.push('ombro + esforço + sintomas cardiorrespiratórios');}\n    if(cond.id==='ombro_pmr'&&idade>=50)score+=2;`;
  must(s,oldPmr,'shoulder cardio scoring');s=s.replace(oldPmr,newPmr);
  const oldCuff=`    if(cond.id==='ombro_manguito'&&temOmbro){\n      if(elevacao&&lateral)score+=3.2;\n      else if(elevacao&&/(dor|doi)/.test(t))score+=2.7;\n      if(decubito&&/(dor|doi)/.test(t))score+=1.2;\n    }`;
  const newCuff=`    if(cond.id==='ombro_manguito'&&temOmbro){\n      if(!elevacaoNegada&&elevacao&&lateral)score+=3.2;\n      else if(!elevacaoNegada&&elevacao&&/(dor|doi)/.test(t))score+=2.7;\n      if(decubito&&/(dor|doi)/.test(t))score+=1.2;\n      if((neuroDistal||cervicalLigada)&&!(elevacao&&lateral&&!elevacaoNegada))score-=3.2;\n      if(toracico&&esforcoCardio&&associadosCardio)score-=4;\n    }`;
  must(s,oldCuff,'shoulder cuff scoring');s=s.replace(oldCuff,newCuff);
  save(path,s);
 }
}

// WRIST / HAND
{
 const path='clinical_reasoning_wrist-3.1.0.js';let s=load(path);
 if(!s.includes("const VERSION='3.1.1-wrist2'")){
  must(s,"const VERSION='3.1.0-wrist1';",'wrist version');s=s.replace("const VERSION='3.1.0-wrist1';","const VERSION='3.1.1-wrist2';");
  s=before(s,"    C('tunel_carpo',96",`    C('punho_mediano_proximal',97,'Neuropatia mediana proximal / síndrome do pronador — diferencial',{bancoId:null,termos:['dor no antebraco com formigamento no polegar indicador e medio','formigamento mediano piora ao pronar','nervo mediano no antebraco'],perguntas:['Há dor/parestesia na face volar proximal do antebraço associada aos sintomas medianos?','Pronação resistida ou carga de flexores do cotovelo/antebraço reproduz a queixa?','O padrão é pouco noturno e não melhora ao sacudir a mão, ao contrário do padrão clássico de túnel do carpo?'],objetivos:['Mapear território mediano incluindo antebraço/palma e função motora','Comparar provocação proximal no antebraço com provocação no túnel do carpo','Screening cervical para excluir fonte ainda mais proximal'],reforca:['sintomas medianos + dor volar do antebraço','provocação com pronação/carga proximal'],enfraquece:['padrão noturno clássico e alívio ao sacudir a mão']}),`,'insert proximal median');
  s=before(s,"    C('tfcc',91",`    C('punho_ecu',92,'Tendão extensor ulnar do carpo (ECU) / instabilidade tendínea — investigar',{bancoId:null,termos:['dor dorsal ulnar no punho com estalo do tendao','tendao pula no lado ulnar do punho','dor no ecu ao girar o antebraco'],perguntas:['A dor é dorsal-ulnar e existe estalo/subluxação tendínea com rotação do antebraço?','Desvio ulnar ou extensão resistida reproduz a dor mais superficialmente que carga profunda do TFCC?'],objetivos:['Localizar ECU versus fóvea/DRUJ','Avaliar carga resistida e estabilidade dinâmica do ECU quando seguro','Diferenciar de TFCC e instabilidade da DRUJ'],reforca:['dor dorsal-ulnar','estalo/subluxação tendínea','rotação/desvio ulnar'],enfraquece:['dor profunda foveal sem estalo tendíneo']}),`,'insert ECU');
  s=before(s,"    C('dequervain',90",`    C('punho_intersecao',91,'Síndrome de interseção dorsal — diferencial de dor radial',{bancoId:null,termos:['dor dorsoradial acima do punho','crepitacao alguns centimetros acima do punho','dor no antebraco dorsal radial com extensao repetitiva'],perguntas:['O ponto doloroso fica alguns centímetros proximal à estiloide radial, no dorso do antebraço, em vez do primeiro compartimento junto ao polegar?','Há crepitação e relação com extensão repetitiva do punho?'],objetivos:['Distinguir topograficamente síndrome de interseção de De Quervain','Provocar de forma graduada com extensão resistida/repetitiva conforme irritabilidade'],reforca:['dor dorsoradial proximal à estiloide','crepitação','extensão repetitiva'],enfraquece:['dor focal no primeiro compartimento junto ao polegar']}),`,'insert intersection');
  s=before(s,"    tunel_carpo:{",`    punho_mediano_proximal:{essencial:['Mapa sensitivo/motor mediano e localização da dor no antebraço','Pronação/carga proximal versus provocação no carpo','Screening cervical'],complementar:['Neurodinâmica e avaliação eletrofisiológica quando indicada'],evitar:['Rotular túnel do carpo por distribuição mediana sem diferenciar compressão proximal']},`,'proximal median matrix');
  s=before(s,"    tfcc:{",`    punho_ecu:{essencial:['Localização dorsal-ulnar do ECU','Carga de extensão/desvio ulnar e rotação','Instabilidade/subluxação tendínea dinâmica quando segura'],complementar:['Ultrassom dinâmico quando clinicamente indicado','Comparação com fóvea/DRUJ'],evitar:['Atribuir todo sintoma ulnar ao TFCC sem localizar a estrutura']},`,'ECU matrix');
  s=before(s,"    dequervain:{",`    punho_intersecao:{essencial:['Localização dorsoradial proximal à estiloide','Crepitação e relação com extensão repetitiva'],complementar:['Extensão resistida/repetitiva conforme tolerância'],evitar:['Confundir com De Quervain apenas por estar no lado radial']},`,'intersection matrix');
  const oldVars=`    const basePolegar=/base do polegar/.test(t);\n    const ulnarDor=/(dor ulnar|lado do mindinho).{0,30}punho|punho.{0,30}(ulnar|lado do mindinho)/.test(t);`;
  const newVars=`    const basePolegar=/base do polegar/.test(t);\n    const noturno=/(?:noite|noturn|acord).{0,50}(?:formig|dormen|mao|dedo)|(?:formig|dormen).{0,50}(?:noite|noturn|acord)/.test(t);\n    const antebracoVolar=/(?:frente|volar|anterior).{0,30}antebraco|antebraco.{0,30}(?:frente|volar|anterior)/.test(t);\n    const pronacaoProvoca=/(?:pron|virar a palma).{0,35}(?:forca|resist|piora|dor|reproduz)|(?:piora|dor|reproduz).{0,35}(?:pron|virar a palma)/.test(t);\n    const medianoProximal=mediano&&antebracoVolar&&pronacaoProvoca;\n    const radialProximal=/(?:dorso radial|dorsoradial).{0,45}(?:antebraco|acima do punho)|(?:antebraco).{0,45}(?:dorso radial|dorsoradial|acima do punho)/.test(t);\n    const crepitacaoRadial=/crepit|rangendo|raspando/.test(t);\n    const ulnarDor=/(dor ulnar|lado do mindinho).{0,30}punho|punho.{0,30}(ulnar|lado do mindinho)/.test(t);\n    const ulnarDorsal=/(?:dorso|dorsal).{0,35}(?:ulnar|lado do mindinho).{0,35}punho|punho.{0,35}(?:dorso|dorsal).{0,35}(?:ulnar|lado do mindinho)/.test(t);\n    const estaloTendineo=/(?:estalo|clique|pula|salta|sublux).{0,35}tendao|tendao.{0,35}(?:estalo|clique|pula|salta|sublux)/.test(t)&&!negado(t,'estalo|clique');`;
  must(s,oldVars,'wrist variables');s=s.replace(oldVars,newVars);
  const oldCTS=`    if(cond.id==='tunel_carpo'){if(mediano)add(4.8,'distribuição mediana');if(mediano&&/(noite|noturn|dirig|celular|sacud)/.test(t))add(1.5,'comportamento típico');if(labelOnly)score=-5;if(ulnar&&!mediano)score-=3;}`;
  const newCTS=`    if(cond.id==='punho_mediano_proximal'){if(medianoProximal)add(5.7,'distribuição mediana + provocação proximal');if(noturno&&/sacud/.test(t))score-=2.5;}\n    if(cond.id==='tunel_carpo'){if(mediano)add(4.8,'distribuição mediana');if(mediano&&/(noite|noturn|dirig|celular|sacud)/.test(t))add(1.5,'comportamento típico');if(labelOnly)score=-5;if(ulnar&&!mediano)score-=3;if(cervical||medianoProximal)score-=5;}`;
  must(s,oldCTS,'wrist CTS scoring');s=s.replace(oldCTS,newCTS);
  const oldTFCC=`    if(cond.id==='tfcc'){if(ulnarDor&&rotCarga&&!ulnar)add(5,'dor ulnar + rotação/carga');if(ulnar)score-=3;}\n    if(cond.id==='instabilidade_escafolunar')`;
  const newTFCC=`    if(cond.id==='punho_ecu'){if(ulnarDorsal&&estaloTendineo&&rotCarga)add(5.9,'dor dorsal-ulnar + instabilidade tendínea dinâmica');}\n    if(cond.id==='tfcc'){if(ulnarDor&&rotCarga&&!ulnar)add(5,'dor ulnar + rotação/carga');if(ulnar)score-=3;if(ulnarDorsal&&estaloTendineo)score-=4;}\n    if(cond.id==='instabilidade_escafolunar')`;
  must(s,oldTFCC,'wrist TFCC scoring');s=s.replace(oldTFCC,newTFCC);
  const oldDeQ=`    if(cond.id==='dequervain'){if(radial&&/(polegar|bebe|abrir pote|potes)/.test(t)&&!trauma)add(4.8,'dor radial + carga do polegar');if(basePolegar&&!radial)score-=1.5;if(trauma)score-=2.5;}`;
  const newDeQ=`    if(cond.id==='punho_intersecao'){if(radialProximal&&crepitacaoRadial&&/(extens|repet|remo|treino|trabalho)/.test(t))add(5.7,'dor dorsoradial proximal + crepitação/carga repetitiva');else if(radialProximal&&/(extens|repet)/.test(t))add(4.4,'dor dorsoradial proximal + extensão repetitiva');}\n    if(cond.id==='dequervain'){if(radial&&/(polegar|bebe|abrir pote|potes)/.test(t)&&!trauma&&!radialProximal)add(4.8,'dor radial + carga do polegar');if(basePolegar&&!radial)score-=1.5;if(trauma)score-=2.5;if(radialProximal)score-=4;}`;
  must(s,oldDeQ,'wrist dequervain scoring');s=s.replace(oldDeQ,newDeQ);
  save(path,s);
 }
}

// CACHE BUST ONLY — preserve loader contract/version and ordering.
{
 const path='screen_loader-1.25.0.js';let s=load(path);
 const changes=[
  ["clinical_reasoning_shoulder-3.1.0.js?v=20260910-lang-r3'","clinical_reasoning_shoulder-3.1.0.js?v=20260910-lang-r3&upperlimb=20260910-r1'"],
  ["clinical_reasoning_elbow-3.1.0.js?v=20260910-r1'","clinical_reasoning_elbow-3.1.0.js?v=20260910-r1&upperlimb=20260910-r1'"],
  ["clinical_reasoning_wrist-3.1.0.js?v=20260910-r1'","clinical_reasoning_wrist-3.1.0.js?v=20260910-r1&upperlimb=20260910-r1'"]
 ];
 for(const [a,b] of changes){if(s.includes(a))s=s.replace(a,b);else if(!s.includes(b))throw new Error('Cache marker missing: '+a);}
 save(path,s);
}
console.log('Upper-limb hardening patch applied.');
